# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True)),
                ('total_price', models.FloatField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartProductMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.CartModel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProductMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.CategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalleryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.GalleryModel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.CartModel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.ClientModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(db_index=True)),
                ('amount', models.IntegerField()),
                ('rating', models.FloatField(db_index=True)),
                ('desc', models.TextField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.GalleryModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecallMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='RecallModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='productrecallmap',
            name='recall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.RecallModel'),
        ),
        migrations.AddField(
            model_name='imagegallerymap',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.ImageModel'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='cover_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.ImageModel'),
        ),
        migrations.AddField(
            model_name='categoryproductmap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.ProductModel'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.GalleryModel'),
        ),
        migrations.AddField(
            model_name='cartproductmap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop_web.ProductModel'),
        ),
    ]
