# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_web', '0004_remove_ordermodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_datetime',
            field=models.DateField(default=datetime.datetime(2016, 7, 9, 14, 58, 20, 848271), editable=False),
        ),
    ]
