# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_web', '0005_ordermodel_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_datetime',
        ),
    ]
