# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_web', '0007_auto_20160709_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to=b''),
        ),
    ]
